# Generated by Django 5.1.4 on 2025-01-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_task_is_completed_remove_task_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
